# Generated by Django 2.0.6 on 2018-07-03 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name': 'Diary', 'verbose_name_plural': 'Diaries'},
        ),
        migrations.AlterModelOptions(
            name='noteprecise',
            options={'verbose_name': 'Note Precise', 'verbose_name_plural': 'Note for each Student'},
        ),
        migrations.AlterField(
            model_name='class',
            name='support',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter', to='note.UserProfile'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='note.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Supporter', 'Supporter'), ('Manager', 'Manager')], default=('Teacher', 'Teacher'), max_length=255),
        ),
    ]
