# Generated by Django 2.0.6 on 2018-06-25 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_diary_noteprecise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='name_course',
        ),
        migrations.AddField(
            model_name='class',
            name='support',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='diary',
            name='time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
